/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import modelo.dao.beans.Categoria;
import modelo.dao.beans.Producto;
import modelo.dao.beans.enums.TipoGestion;
import modelo.gestionBd.GestionSql;
import modelo.servicios.CategoriaServicio;
import modelo.servicios.ProductoServicio;

/**
 *
 * @author brand
 */
public class ProductoVista extends javax.swing.JFrame {

    private ProductoServicio productoServicio;
    private CategoriaServicio categoriaServicio;
    private int row = -1;

    /**
     * Creates new form Producto
     */
    public ProductoVista() {
        initComponents();
        try {
            GestionSql gestionSql = new GestionSql();
            gestionSql.openConnection();
            productoServicio = new ProductoServicio();
            categoriaServicio = new CategoriaServicio();
            List<Producto> productos = productoServicio.gestionarProducto(null, TipoGestion.LISTAR);
            cargarProductosEnTabla(productos);
        } catch (SQLException ex) {
            Logger.getLogger(CategoriaVista.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelProducto = new javax.swing.JPanel();
        jLabelSeleccioneProducto = new javax.swing.JLabel();
        jTextFieldProducto = new javax.swing.JTextField();
        jButtonModificarProducto = new javax.swing.JButton();
        jButtonBorrarProducto = new javax.swing.JButton();
        jScrollPaneTablaProducto = new javax.swing.JScrollPane();
        jTablePresentaProductos = new javax.swing.JTable();
        jLabelIdCategoria = new javax.swing.JLabel();
        jLabelProducto = new javax.swing.JLabel();
        jButtonInsertarProducto = new javax.swing.JButton();
        jTextFieldIdCategoria = new javax.swing.JTextField();
        jTextFieldImagen = new javax.swing.JTextField();
        jLabelProducto1 = new javax.swing.JLabel();

        setTitle("Gestion Producto");

        jLabelSeleccioneProducto.setText("Seleccione Producto");

        jTextFieldProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldProductoActionPerformed(evt);
            }
        });

        jButtonModificarProducto.setText("Modificar");
        jButtonModificarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarProductoActionPerformed(evt);
            }
        });

        jButtonBorrarProducto.setText("Borrar");
        jButtonBorrarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarProductoActionPerformed(evt);
            }
        });

        jTablePresentaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTablePresentaProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePresentaProductosMouseClicked(evt);
            }
        });
        jScrollPaneTablaProducto.setViewportView(jTablePresentaProductos);

        jLabelIdCategoria.setText("Id categoria");

        jLabelProducto.setText("Producto");

        jButtonInsertarProducto.setText("Insertar");
        jButtonInsertarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsertarProductoActionPerformed(evt);
            }
        });

        jTextFieldImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldImagenActionPerformed(evt);
            }
        });

        jLabelProducto1.setText("Imagen");

        javax.swing.GroupLayout jPanelProductoLayout = new javax.swing.GroupLayout(jPanelProducto);
        jPanelProducto.setLayout(jPanelProductoLayout);
        jPanelProductoLayout.setHorizontalGroup(
            jPanelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProductoLayout.createSequentialGroup()
                .addGroup(jPanelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneTablaProducto)
                    .addGroup(jPanelProductoLayout.createSequentialGroup()
                        .addGroup(jPanelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelProductoLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabelSeleccioneProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelProductoLayout.createSequentialGroup()
                                .addGroup(jPanelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelProductoLayout.createSequentialGroup()
                                        .addComponent(jLabelIdCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldIdCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabelProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanelProductoLayout.createSequentialGroup()
                                        .addGap(57, 57, 57)
                                        .addComponent(jButtonInsertarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(111, 111, 111)
                                        .addComponent(jButtonModificarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButtonBorrarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanelProductoLayout.createSequentialGroup()
                                        .addComponent(jLabelProducto1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 219, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelProductoLayout.setVerticalGroup(
            jPanelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelProductoLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabelSeleccioneProducto)
                .addGap(18, 18, 18)
                .addComponent(jScrollPaneTablaProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelIdCategoria)
                    .addComponent(jTextFieldIdCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelProducto)
                    .addComponent(jTextFieldProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelProducto1)
                    .addComponent(jTextFieldImagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonInsertarProducto)
                    .addComponent(jButtonModificarProducto)
                    .addComponent(jButtonBorrarProducto))
                .addGap(252, 252, 252))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanelProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldProductoActionPerformed

    private void jButtonModificarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarProductoActionPerformed
        if (row != -1 && jTextFieldProducto.getText() != null && jTextFieldProducto.getText().length() > 0) {
            try {
                String nombre = (String) jTablePresentaProductos.getModel().getValueAt(row, 1);
                Producto producto = productoServicio.getProductoByNombre(nombre);
                producto.setNombre(jTextFieldProducto.getText());
                productoServicio.gestionarProducto(producto, TipoGestion.MODIFICAR);
                List<Producto> productos = productoServicio.gestionarProducto(null, TipoGestion.LISTAR);
                cargarProductosEnTabla(productos);
            } catch (SQLException ex) {
                Logger.getLogger(CategoriaVista.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_jButtonModificarProductoActionPerformed

    private void jButtonInsertarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsertarProductoActionPerformed
        String nombreProducto = jTextFieldProducto.getText();
        if (nombreProducto != null && nombreProducto.length() > 0) {
            try {
                Producto producto = new Producto();
                producto.setNombre(nombreProducto);
                productoServicio.gestionarProducto(producto, TipoGestion.INSERTAR);
                List<Producto> productos = productoServicio.gestionarProducto(null, TipoGestion.LISTAR);
                cargarProductosEnTabla(productos);
            } catch (SQLException ex) {
                Logger.getLogger(CategoriaVista.class.getName()).log(Level.SEVERE, null, ex);
            }
//Condicion para cambiar ID
        }
    }//GEN-LAST:event_jButtonInsertarProductoActionPerformed

    private void jTablePresentaProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePresentaProductosMouseClicked
        JTable source = (JTable) evt.getSource();
        row = source.rowAtPoint(evt.getPoint());
        String nombre = (String) jTablePresentaProductos.getModel().getValueAt(row, 2);
        jTextFieldProducto.setText(nombre);
        String nombreCategoria = (String) jTablePresentaProductos.getModel().getValueAt(row, 1);
        try {
            Categoria categoria = categoriaServicio.getCategoriaByNombre(nombreCategoria);
            jTextFieldIdCategoria.setText(categoria.getId() + "");
        } catch (SQLException ex) {
            Logger.getLogger(ProductoVista.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        String nombreImagen = (String)jTablePresentaProductos.getModel().getValueAt(row, 3);
        jTextFieldImagen.setText(nombreImagen);
    }//GEN-LAST:event_jTablePresentaProductosMouseClicked

    private void jButtonBorrarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarProductoActionPerformed
        if (row != -1 && jTextFieldProducto.getText() != null && jTextFieldProducto.getText().length() > 0) {
            try {
                String nombre = (String) jTablePresentaProductos.getModel().getValueAt(row, 1);
                Producto producto = productoServicio.getProductoByNombre(nombre);
                productoServicio.gestionarProducto(producto, TipoGestion.BORRAR);
                List<Producto> productos = productoServicio.gestionarProducto(null, TipoGestion.BORRAR);
                cargarProductosEnTabla(productos);
            } catch (SQLException ex) {
                Logger.getLogger(CategoriaVista.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_jButtonBorrarProductoActionPerformed

    private void jTextFieldImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldImagenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldImagenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductoVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductoVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductoVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductoVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductoVista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBorrarProducto;
    private javax.swing.JButton jButtonInsertarProducto;
    private javax.swing.JButton jButtonModificarProducto;
    private javax.swing.JLabel jLabelIdCategoria;
    private javax.swing.JLabel jLabelProducto;
    private javax.swing.JLabel jLabelProducto1;
    private javax.swing.JLabel jLabelSeleccioneProducto;
    private javax.swing.JPanel jPanelProducto;
    private javax.swing.JScrollPane jScrollPaneTablaProducto;
    private javax.swing.JTable jTablePresentaProductos;
    private javax.swing.JTextField jTextFieldIdCategoria;
    private javax.swing.JTextField jTextFieldImagen;
    private javax.swing.JTextField jTextFieldProducto;
    // End of variables declaration//GEN-END:variables

    private void cargarProductosEnTabla(List<Producto> productos) {
        Object[][] data = new Object[(int) productos.size()][4];

        for (int j = 0; j < productos.size(); j++) {
            Producto producto = productos.get(j);
            for (int i = 0; i < 4; i++) {
                if (i == 0) {
                    data[j][i] = producto.getId();
                } else if (i == 1) {
                    Categoria categoria = new Categoria();
                    categoria.setId(producto.getIdCategoria());
                    List<Categoria> categorias = null;
                    try {
                        categorias = categoriaServicio.gestionarCategoria(categoria, TipoGestion.CONSULTAR);
                    } catch (SQLException ex) {
                        Logger.getLogger(ProductoVista.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    data[j][i] = categorias.get(0).getNombre();
                } else if (i == 2) {
                    data[j][i] = producto.getNombre();
                } else {
                    data[j][i] = producto.getImagen();
                }
            }
        }

        DefaultTableModel defaultTableModel = new DefaultTableModel(data, new String[]{"Id Producto", "Categoria", "Producto", "Imagen"}) {
            @Override
            public Class getColumnClass(int column) {
                return getValueAt(0, column).getClass();
            }
        };
        jTablePresentaProductos.setModel(defaultTableModel);

    }

}
